version: "3.8"

services:

  node1:
    image: kottig/blockchain
    container_name: node1
    network_mode: host
    command: "1"

  node2:
    image: kottig/blockchain
    container_name: node2
    network_mode: host
    command: "2"

  node3:
    image: kottig/blockchain
    container_name: node3
    network_mode: host
    command: "3"
    depends_on:
      - node1
      - node2

